DROP TABLE IF EXISTS payment_methods CASCADE;
DROP TABLE IF EXISTS carts CASCADE;
DROP TABLE IF EXISTS cart_items CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    state VARCHAR(2) NOT NULL CHECK (STATE IN ('CO', 'CA'))
);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cost NUMERIC(10, 2) NOT NULL
);

CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL CHECK (QUANTITY > 0),
    has_warranty BOOLEAN DEFAULT FALSE,
    warranty_years INTEGER DEFAULT 0,
    has_gift_wrap BOOLEAN DEFAULT FALSE,
    discount_percentage NUMERIC(5, 2) DEFAULT 0.00,
    FOREIGN KEY (cart_id) REFERENCES carts(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    payment_type VARCHAR(50) NOT NULL,
    balance NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    payment_email VARCHAR(255),
    payment_password VARCHAR(255),
    payment_card_number VARCHAR(20),
    payment_card_pin VARCHAR(10),
    payment_card_name VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(id),
    UNIQUE (user_id, payment_type)
);